name: build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build-mcpb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4
      - uses: actions/setup-node@v5
        with:
          node-version-file: .node-version
          cache: "pnpm"
      - run: pnpm install --frozen-lockfile
      - run: pnpm build:mcpb
      - uses: actions/upload-artifact@v4
        with:
          path: build/kintone-mcp-server.mcpb
          name: kintone-mcp-server.mcpb
          retention-days: 3

  build-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4
      - uses: actions/setup-node@v5
        with:
          node-version-file: .node-version
          cache: "pnpm"
      - run: pnpm install --frozen-lockfile
      - run: pnpm pack
      - uses: actions/upload-artifact@v4
        with:
          path: "kintone-mcp-server-*.tgz"
          name: kintone-mcp-server.tgz
          retention-days: 3
