name: release

on:
  push:
    branches:
      - main

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - uses: actions/create-github-app-token@v2
        id: create-iat
        with:
          app-id: ${{ secrets.NPM_RELEASER_GITHUB_APP_ID}}
          private-key: ${{ secrets.NPM_RELEASER_GITHUB_APP_KEY }}
      - name: Release Please
        id: release
        uses: googleapis/release-please-action@a02a34c4d625f9be7cb89156071d8567266a2445 # v4.2.0
        with:
          token: ${{ steps.create-iat.outputs.token }}

  build-and-publish-container:
    permissions:
      packages: write # To push Docker images to ghcr.io
    needs: release-please
    if: needs.release-please.outputs.release_created
    uses: ./.github/workflows/publish-image.yaml
    with:
      tags: "${{ needs.release-please.outputs.tag_name }},latest"
      push: true

  build-and-upload-dxt-to-release:
    needs: release-please
    if:  needs.release-please.outputs.release_created
    runs-on: ubuntu-latest
    permissions:
      contents: write # To upload release assets
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: "pnpm"
      - run: pnpm install --frozen-lockfile
      - run: pnpm build:dxt
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ needs.release-please.outputs.tag_name }} \
            build/kintone-mcp-server.dxt \
            --clobber

  # TODO: Remove false when ready to publish
  publish-npm-package:
    name: Publish to npm
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    needs: release-please
    if: needs.release-please.outputs.release_created && false
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: "pnpm"
      - run: pnpm install --frozen-lockfile
      - name: Configure npm user
        run: npm config set "//registry.npmjs.org/:_authToken=${NPM_TOKEN}"
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: pnpm build
      - run: pnpm -r publish --access public
        env:
          NPM_CONFIG_PROVENANCE: true
