name: publish-image
on:
  workflow_call:
    inputs:
      tags:
        description: 'Comma-separated list of tags for the Docker image (e.g., "1.0.0,latest")'
        required: true
        type: string
      push:
        description: "Whether to push the Docker image to registry"
        required: false
        type: boolean
        default: true

defaults:
  run:
    shell: bash -eo pipefail {0}

jobs:
  generate-tags:
    runs-on: ubuntu-latest
    outputs:
      tags: ${{ steps.generate-tags.outputs.result }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Generate tags
        id: generate-tags
        env:
          IMAGE_NAME: ghcr.io/kintone/mcp-server
          TAGS: "${{ inputs.tags }}"
        run: |
          IFS=',' read -ra TAG_ARRAY <<< "$TAGS"
          FULL_TAGS=""
          for tag in "${TAG_ARRAY[@]}"; do
            if [ -n "$FULL_TAGS" ]; then
              FULL_TAGS="$FULL_TAGS,$IMAGE_NAME:$tag"
            else
              FULL_TAGS="$IMAGE_NAME:$tag"
            fi
          done
          echo "result=$FULL_TAGS" >> "$GITHUB_OUTPUT"

  build-and-publish-container:
    needs: generate-tags
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # To push an image to ghcr.io
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Login to GitHub Container Registry
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3

      - name: Build and push Docker image
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6
        with:
          context: .
          file: ./docker/Dockerfile
          provenance: false
          # amd64とarm64の両方でビルドする
          platforms: "linux/amd64,linux/arm64"
          push: ${{ inputs.push }}
          tags: ${{ needs.generate-tags.outputs.tags }}
        env:
          DOCKER_BUILD_SUMMARY: false
